# Data cleaning 1

In [ ]:
import pandas as pd
import numpy as np
DataFrame = df

In [3]:
df = pd.read_csv("C:\\Users\SANDY\Downloads\sales_data_dirty (1).csv")
df

,order_id,order_date,customer_name,city,category,quantity,revenue,cost,profit,payment_method,returned
0,1001,2026-01-05,Rahul,Hyderabad,Electronics,2.0,40000,30000,10000,UPI,No
1,1002,2026-01-07,Priya,hyderabad,electronics,1.0,25000,18000,7000,Cash,No
2,1003,2026-01-10,Amit,HYDERABAD,Clothing,3.0,6000,4000,2000,UPI,Yes
3,1004,2026-01-12,Sneha,Bangalore,Clothing,2.0,5000,3000,2000,Card,No
4,1005,2026-01-15,Ravi,Mumbai,Electronics,1.0,45000,35000,10000,UPI,No
5,1006,2026-01-18,Anjali,Chennai,Food,5.0,2500,1500,1000,Cash,No
6,1007,2026-01-20,Vikram,Delhi,Electronics,2.0,50000,38000,12000,Card,Yes
7,1008,2026-01-22,Neha,Hyderabad,Clothing,NaN,8000,5000,3000,UPI,No
8,1009,2026-01-25,Arjun,Pune,Electronics,1.0,30000,22000,8000,Cash,No
9,1010,2026-02-01,Meena,Mumbai,Food,10.0,5000,3000,2000,UPI,No
10,1011,2026-02-03,Rohit,Bangalore,Electronics,2.0,40000,30000,10000,Card,No
11,1012,2026-02-05,Kiran,Chennai,Clothing,4.0,12000,8000,4000,UPI,Yes
12,1013,2026-02-07,Divya,Hyderabad,Food,3.0,1500,900,600,Cash,No
13,1014,2026-02-10,Arun,Delhi,Electronics,1.0,abc,20000,10000,Card,No
14,1015,2026-02-12,Sonal,Mumbai,Clothing,2.0,7000,4500,2500,UPI,No
15,1016,2026-02-15,Manoj,Hyderabad,Electronics,-1.0,20000,15000,5000,Cash,No
16,1017,2026-02-18,Pooja,Bangalore,Food,6.0,3000,1800,1200,UPI,No
17,1018,2026-02-20,Varun,Chennai,Electronics,2.0,60000,45000,15000,Card,No
18,1019,2026-02-22,Swati,Delhi,Clothing,3.0,9000,6000,3000,Cash,Yes
19,1020,2026-02-25,Ramesh,Hyderabad,Food,4.0,2000,1200,800,UPI,No
20,1015,2026-02-12,Sonal,Mumbai,Clothing,2.0,7000,4500,2500,UPI,No
21,1021,invalid_date,Ajay,Hyderabad,Electronics,1.0,35000,25000,10000,Card,No
22,1022,2026-03-02,NaN,Mumbai,Food,5.0,2500,1500,1000,Cash,No
23,1023,2026-03-05,Swathi,HYDERABAD,Clothing,2.0,6000,4000,2000,UPI,No
24,1024,2026-03-08,Prakash,Bangalore,Electronics,100.0,5000000,3000000,2000000,Card,No
25,1025,2026-03-10,Nisha,Chennai,Food,2.0,1000,700,500,UPI,Maybe

In [5]:
df.head(5)

,order_id,order_date,customer_name,city,category,quantity,revenue,cost,profit,payment_method,returned
0,1001,2026-01-05,Rahul,Hyderabad,Electronics,2.0,40000,30000,10000,UPI,No
1,1002,2026-01-07,Priya,hyderabad,electronics,1.0,25000,18000,7000,Cash,No
2,1003,2026-01-10,Amit,HYDERABAD,Clothing,3.0,6000,4000,2000,UPI,Yes
3,1004,2026-01-12,Sneha,Bangalore,Clothing,2.0,5000,3000,2000,Card,No
4,1005,2026-01-15,Ravi,Mumbai,Electronics,1.0,45000,35000,10000,UPI,No

In [6]:
df.tail(5)

,order_id,order_date,customer_name,city,category,quantity,revenue,cost,profit,payment_method,returned
21,1021,invalid_date,Ajay,Hyderabad,Electronics,1.0,35000,25000,10000,Card,No
22,1022,2026-03-02,NaN,Mumbai,Food,5.0,2500,1500,1000,Cash,No
23,1023,2026-03-05,Swathi,HYDERABAD,Clothing,2.0,6000,4000,2000,UPI,No
24,1024,2026-03-08,Prakash,Bangalore,Electronics,100.0,5000000,3000000,2000000,Card,No
25,1025,2026-03-10,Nisha,Chennai,Food,2.0,1000,700,500,UPI,Maybe

In [7]:
df.shape

(26, 11)

In [8]:
df.columns

Index(['order_id', 'order_date', 'customer_name', 'city', 'category',
       'quantity', 'revenue', 'cost', 'profit', 'payment_method', 'returned'],
      dtype='object')

In [9]:
df.dtypes

order_id            int64
order_date         object
customer_name      object
city               object
category           object
quantity          float64
revenue            object
cost                int64
profit              int64
payment_method     object
returned           object
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        26 non-null     int64
 1   order_date      26 non-null     object
 2   customer_name   25 non-null     object
 3   city            26 non-null     object
 4   category        26 non-null     object
 5   quantity        25 non-null     float64
 6   revenue         26 non-null     object
 7   cost            26 non-null     int64
 8   profit          26 non-null     int64
 9   payment_method  26 non-null     object
 10  returned        26 non-null     object
dtypes: float64(1), int64(3), object(7)
memory usage: 2.4+ KB

In [11]:
df.describe()

          order_id    quantity          cost        profit
count    26.000000   25.000000  2.600000e+01  2.600000e+01
mean   1013.076923    6.600000  1.279846e+05  8.173462e+04
std       7.221762   19.576772  5.859316e+05  3.912738e+05
min    1001.000000   -1.000000  7.000000e+02  5.000000e+02
25%    1007.250000    2.000000  3.000000e+03  2.000000e+03
50%    1013.500000    2.000000  5.500000e+03  3.000000e+03
75%    1018.750000    4.000000  2.425000e+04  1.000000e+04
max    1025.000000  100.000000  3.000000e+06  2.000000e+06

In [13]:
df.select_dtypes(include="number").columns # numerical columns

Index(['order_id', 'quantity', 'cost', 'profit'], dtype='object')

In [14]:
df.select_dtypes(include="object").columns  #catagericl columns

Index(['order_date', 'customer_name', 'city', 'category', 'revenue',
       'payment_method', 'returned'],
      dtype='object')

In [15]:
df.isnull().sum() #missing values

order_id          0
order_date        0
customer_name     1
city              0
category          0
quantity          1
revenue           0
cost              0
profit            0
payment_method    0
returned          0
dtype: int64

In [16]:
df.isnull().mean()*100  #percentage

order_id          0.000000
order_date        0.000000
customer_name     3.846154
city              0.000000
category          0.000000
quantity          3.846154
revenue           0.000000
cost              0.000000
profit            0.000000
payment_method    0.000000
returned          0.000000
dtype: float64

In [18]:
df[df.isnull().any(axis=1)] #rows contain missing values

,order_id,order_date,customer_name,city,category,quantity,revenue,cost,profit,payment_method,returned
7,1008,2026-01-22,Neha,Hyderabad,Clothing,NaN,8000,5000,3000,UPI,No
22,1022,2026-03-02,NaN,Mumbai,Food,5.0,2500,1500,1000,Cash,No

In [20]:
df.isnull().sum().idxmax()  #column with high missing value

'customer_name'

In [21]:
df["revenue"]=df["revenue"].fillna(df["revenue"].mean())  #fill numerical missing values with mean

TypeError: Could not convert string '40000250006000500045000250050000800030000500040000120001500abc700020000300060000900020007000350002500600050000001000' to numeric

In [23]:
df["cost"]=df["cost"].fillna(df["cost"].median()) #fill numerical missing values with mwdian

In [24]:
df["city"] = df["city"].fillna(df["city"].mode()[0])# fill with mode categorical missing value

In [25]:
df = df.dropna(subset=["customer_id","order_date"]) #remove rows with missing imp values

KeyError: ['customer_id']

In [26]:
df.isnull().sum() #verify moissing values

order_id          0
order_date        0
customer_name     1
city              0
category          0
quantity          1
revenue           0
cost              0
profit            0
payment_method    0
returned          0
dtype: int64